name: CI

#Workflow triggered when a tag is pushed that looks like 'v1.0.0'
on:
  push:
    tags:
      - 'v*.*.*'
      
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    steps:
      # Pull code from the repository
      - name: Checkout
        uses: actions/checkout@v4
      # Setup .NET 9
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
        env:
          NUGET_AUTH_TOKEN: ${secrets.NUGET_API_KEY}
      - name: Set VERSION_NUMBER variable from tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        
      - name: Strip V from Version NUMBER
        run: echo "VERSION=${RELEASE_VERSION#v}" >> $GITHUB_ENV
        
      - name: Build
        run: dotnet build --configuration Release /p:Version=${{ env.VERSION }}
        
      - name: Test
        run: dotnet test --configuration Release /p:Version=${{ env.VERSION }} --no-build
        
      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${{ env.VERSION }} --no-build --output ./packages
        
      - name: NuGet-Pakete zu GitHub Packages veröffentlichen
        run: |
          # Überprüfe die Länge des Tokens (sollte > 0 sein)
          echo "Token length: ${#NUGET_API_KEY}"
          for file in ./packages/*.nupkg; do
            echo "Pushing package: $file"
            dotnet nuget push "$file" \
              --api-key "$NUGET_API_KEY" \
              --source "https://nuget.pkg.github.com/Beerhunt-Studios/index.json" \
              --skip-duplicate
          done